name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  build-tdlib:
    uses: ./.github/workflows/build-tdlib.yml

  release_github:
    runs-on: ubuntu-latest
    needs: build-tdlib
    steps:
      - name: Download artifacts
        run: gh run download ${{ github.run_id }} -R $REPO
      - name: Zip artifacts
        run: find * -maxdepth 0 -type d -execdir mv '{}' tdlib \; -execdir zip -r -m -6 '{}.zip' 'tdlib' \;
      - name: Create release
        run: gh release create ${{ github.ref_name }} -R $REPO --generate-notes ./*.zip

  # release_crates:
  #   runs-on: ubuntu-latest
  #   needs: release_github
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Publish to crates.io
  #       run: |
  #         cargo login ${{ secrets.CRATES_IO_TOKEN }}
  #         cargo publish --package tdlib-rs-parser
  #         cargo publish --package tdlib-rs-gen
  #         cargo publish --no-verify --package tdlib-rs
